# Generated by Django 3.1.4 on 2020-12-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='image',
            new_name='avatar',
        ),
    ]
